// Code generated by goctl. DO NOT EDIT.
package types

type UserLogin struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type UserLoginres struct {
	Token string `json:"token"`
}

type UserInfo struct {
	Username string `json:"username"`
	Password string `json:"password"`
}
